server:
  port: 2222
  
spring:
  application:
    name: GRRET-API
    
  boot:
    admin:
      client:
        url: http://localhost:9090/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'